### ISSUE TITLE
Why does fdroid list the `read your contacts` permission?

### ISSUE THREAD

**Issue by bernhardreiter** [SecUSo/privacy-friendly-boardgame-clock#39]
https://f-droid.org/en/packages/org.secuso.privacyfriendlyboardgameclock/

version 1.0

**Comment by Kamuno** [comment]
The board game clock offers to import names and icons from your contacts to play.

**Comment by bernhardreiter** [comment]
@Kamuno thanks for the answer. It would be cool to explain this in the description, because it seems to be in contrast to https://secuso.aifb.kit.edu/Brettspieluhr.php where it says that only the permission for doing a backup are needed.

And indeed why would a boardgamecloak need names and icons to play? (I can imagine useful things, but this is how it starts, does it? ;-) Seriously this is an interesting aspect in regard of the stated privacy mission of the group of apps, and thus an more elaborate explanation maybe useful. Thanks for caring for privacy and offering Free Software - it is appreciated!)

**Comment by Kamuno** [comment]
Thanks for pointing this out. We will fix the discrepancy in the description.

You are indeed correct, this is how it starts. However, all the data of every privacy friendly app is always stored locally and never sent to any server. This is one of the core principles of the Privacy Friendly Apps. So the user has full control over their data. The contact permission in this specific case is also optional and does not need to be granted for the app to be functional.

**Comment by bernhardreiter** [comment]
If it is optional, it would be nice to point this out. (And can I deselect some permissions when the app asks for it during installation? I think I remember that I've couldn't, so if I would want to not use that optional feature, I'd have to disable this in the settings somewhere. The main point is that people think about what permissions an apps needs.)

**Comment by Kamuno** [comment]
Depends on the Android Version you are using. Versions of Android 6 onwards support runtime permissions. This means that you can grant access to permissions during runtime of the application and do not have to accept everything at the start.
